name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.24.x"]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: SQNS_DB
          MYSQL_USER: SQNS_User
          MYSQL_PASSWORD: 123
        ports:
          - 3306:3306
        options: >-
          --health-cmd=mysqladmin ping
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Wait for MySQL to start
        run: |
          until nc -z services.mysql.port-3306 3306; do
            sleep 1
          done

      - name: Set environment variables
        run: |
          echo "SQNStest_MYSQL_ROOT_PASSWORD=rootpassword" >> $GITHUB_ENV
          echo "SQNStest_DB_Host_PORT=services.mysql.port-3306" >> $GITHUB_ENV

      - name: Run local server
        run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 50
          go test -run ^TestServer$ ./tests

      - name: Run database tests
        run: |
          go test -run ^TestInitDB$ ./tests
          go test -run ^TestCheckTableExists$ ./tests
          go test -run ^TestIndexes$ ./tests
