name: Go with MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]

    services:
      mysql:
        image: mysql:9.4.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: SQNS_DB
          MYSQL_USER: SQNS_User
          MYSQL_PASSWORD: 123
          MYSQL_PORT: 3306
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy

    - name: Wait for MySQL to start
      run: |
        until mysqladmin ping -h 127.0.0.1 -P3306 -uroot -prootpassword &> /dev/null; do
          echo "Waiting for MySQL to start..."
          sleep 1
        done

    - name: Run local server
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 50
        go test -run ^TestServer$ ./tests

    - name: Run database tests
      run: |
        go test -run ^TestInitDB$ ./tests
        go test -run ^TestIndexes$ ./tests
